subconfigs:
    - model: base
    - training: base
flyconfig:
    run:
        # Specify the working directory
        # ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
        dir: ./outputs/${task.name}
task:
    name: mnist-example
    datadir: /tmp