name: torchfly
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pytorch
  - torchvision
#  - cudatoolkit=10.1
  - pip:
    - ray
    - regex
    - transformers
    - colorlog
    - tensorboard
    - tqdm
    - gdown
    - scikit-learn
    - overrides
    - pyarrow